### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Dimylka** [netbox-community/netbox-acls#158] opened 2023-07-28 09:28 UTC
### NetBox access-list plugin version

v1.3.0

### NetBox version

v.3.5.2

### Steps to Reproduce

Hi! (sorry for my bad english) 
I've got some proplems with plugin by API
Fist of all i've created host "Webmin" by netbox web interface  

Then i've created  ACL "Webmin_ACL" by netbox API and attach them to host  "Webmin" 
curl -X POST -H "Authorization: Token ********" -H "Content-Type: application/json" -H "Accept: application/json; indent=4" https://netbox.local/api/plugins/access-lists/access-lists/ --data '{"name": "Webmin_ACL", "display": "Webmin_ACL", "assigned_object_type": "virtualization.virtualmachine", "assigned_object_id": 1, "type": "extended" }'

ACL "Webmin_ACL" was created with id "access_list": 7 

Then i've tried to create ACL Extended Rule  by netbox API 
curl -X POST -H "Authorization: Token *******" -H "Content-Type: application/json" -H "Accept: application/json; indent=4" https://netbox.local/api/plugins/access-lists/extended-acl-rules/ --data '{"access_list": 7, "index": 1, "action": "permit", "destination_ports": [100]}'

But got error
 "destination_ports": [
        "Action is set to remark, Destination Ports CANNOT be set."
    ]

Query whithout "destination_ports": [100] will create ACL Extended Rule normally
curl -X POST -H "Authorization: Token ********" -H "Content-Type: application/json" -H "Accept: application/json; indent=4" https://netbox.local/api/plugins/access-lists/extended-acl-rules/ --data '{"access_list": 7, "index": 1, "action": "deny"}'

Please tell me what am i doing wrong?

### Expected Behavior

ACL Extended Rule with "destination_ports" will created normally

### Observed Behavior

 "destination_ports": [
        "Action is set to remark, Destination Ports CANNOT be set."
    ]

**Comment by Dimylka** [comment] 2023-07-28 14:05
I've disabled "Remark" check at /opt/netbox/venv/lib/python3.10/site-packages/netbox_acls/api/serializers.py after that it works!

**Comment by cs-1** [comment] 2024-04-12 05:07
The bug is the one found here: https://github.com/netbox-community/netbox-acls/issues/190 A colleague of mine created a pull request to fix this.

**Comment by jsenecal** [comment] 2024-04-29 19:09
Closing as duplicate of #190 which has better documentation

**Closed as not planned by jsenecal** 2024-04-29 19:09 UTC
Labels: bug
